
alias l="ls -halp"
alias ll="ls -hlp"
alias lm="ls -hp"

alias ds="du -khd 1 . | sort -h"

alias gs='git status'
alias gl='git log'
alias glg='git log --graph'
alias glp='git log --pretty=oneline'

alias fetch_pull='git fetch && git pull'

alias dockerls="docker container ls -a"
alias dockeri="docker image"

alias dc="docker-compose"

export GOTO_EDITOR="vim"

case "$(uname -s)" in
    Linux)

		export ANDROID_HOME=$HOME/Android/Sdk

		;;
	Darwin)
		export ANDROID_HOME="$HOME/Library/Android/sdk"
		export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home"

		;;
esac

export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

[[ -f /home/linuxbrew/.linuxbrew/bin/brew ]] && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

export GTK_IM_MODULE=cedilla
export QT_IM_MODULE=cedilla
