# Just a reminder on redirection of streams
# 0 - stdin, the standard input stream.
# 1 - stdout, the standard output stream.
# 2 - stderr, the standard error stream.


alias l="ls -halp"
alias ll="ls -hlp"
alias lm="ls -hp"

# alias ds="du -khd 1 . | sort -h"
function ds(){
    echo "[>] Command: du -khd 1 $@ | sort -h\n"

    du -khd 1 $@ | sort -h
}

alias gs='git status'
alias gl='git log'
alias gr='git restore'
alias gco='git checkout'
alias glg='git log --graph'
alias glp='git log --pretty=oneline'

# alias fetch_pull='git fetch $@ && git pull $@'
function fetch_pull(){
    echo "[>] Command: git fetch $@ && git pull $@\n"
    git fetch $@ && git pull $@
}

alias podmanlsa="podman container ls -a"
alias dockerlsa="docker container ls -a"
alias dockerls="docker container ls --format 'table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Names}}'"
alias dockeri="docker image"

alias dc="docker-compose"

if ! command -v pbcopy 1>/dev/null 2>&1; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi

case "$(uname -s)" in
    Linux)

		export ANDROID_HOME=$HOME/Android/Sdk
        export GTK_IM_MODULE=cedilla
        export QT_IM_MODULE=cedilla

		;;
	Darwin)
		export ANDROID_HOME="$HOME/Library/Android/sdk"

		;;
esac

if [ -d $ANDROID_HOME/tools ]; then
    export PATH=$PATH:$ANDROID_HOME/tools
    export PATH=$PATH:$ANDROID_HOME/platform-tools
fi

LINUX_BREW_BIN=/home/linuxbrew/.linuxbrew/bin

if [[ -d $LINUX_BREW_BIN ]] && [[ -x $LINUX_BREW_BIN/brew ]]; then
    export PATH=$PATH:$LINUX_BREW_BIN
    eval $($LINUX_BREW_BIN/brew shellenv)
fi

function see_certificate() {
    command_name=$0
    domain=$1
    if [ -z ${1+x} ]; then
        echo "[!] Usage: $command_name <domain.tld>"
        echo "[!] Example: $command_name google.com"
    elif command -v openssl 1>/dev/null 2>&1; then
        echo "[>] Showing certificate for \"$domain\" with Openssl."
        echo | openssl s_client -showcerts -servername gnupg.org -connect $domain:443 2>/dev/null | openssl x509 -inform pem -noout -text | less
    else
        echo "This script depends on OpenSSL"
    fi
}

function b64_decode() {
    command_name=$0
    string=$1
    if [ -z ${1+x} ]; then
        echo "[!] Usage: $command_name <base64string>"
        echo "[!] Example: $command_name SGVsbG8gV29ybGQ="
    elif command -v openssl 1>/dev/null 2>&1; then
        echo "[>] Showing base64 decode for \"$string\" with Openssl."
        echo $string | openssl base64 -d
    else
        echo "This script depends on OpenSSL"
    fi
}

function b64_encode() {
    command_name=$0
    string=$1
    if [ -z ${1+x} ]; then
        echo "[!] Usage: $command_name <ordinal_string>"
        echo "[!] Example: $command_name \"Hello World\""
    elif command -v openssl 1>/dev/null 2>&1; then
        echo "[>] Showing base64 decode for \"$string\" with Openssl."
        echo -n $string | openssl base64
    else
        echo "This script depends on OpenSSL"
    fi
}

export PYTHONOPTIMIZE=1

function codeclimate() {
    # Codeclimate CLI expects docker socket connection. Does not work with podman
    command_name=$0
    args=$*
    if [ -z ${1+x} ]; then
        echo "[!] Usage: $command_name <command>"
        echo "[!] Example: $command_name analyze -f html > var/codeclimate.html"
    elif command -v openssl 1>/dev/null 2>&1; then
        echo "[>] Running Codeclimate CLI with args \"$args\" with Docker."
        docker run \
            --interactive --tty --rm \
            --env CODECLIMATE_CODE="$PWD" \
            --volume "$PWD":/code \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --volume /tmp/cc:/tmp/cc \
            codeclimate/codeclimate \
            $*
    else
        echo "This script depends on docker"
    fi
}

function swaggerui() {
    command_name=$0
    openapi_path=$1
    if [ -z ${1+x} ]; then
        echo "[!] Usage: $command_name <path/openapi.yaml>"
        echo "[!] Example: $command_name ./openapi.yaml"
    elif command -v podman 1>/dev/null 2>&1; then
        final_path=`realpath $openapi_path`

        if [[ -f $final_path ]]; then
            echo "[>] Showing SwaggerUI for \"$openapi_path\" with podman on port 8090."
            podman run \
                -itd \
                --rm \
                --name swaggerui \
                -p 8090:8080 \
                -e API_URL=doc/openapi.yaml \
                -v $final_path:/usr/share/nginx/html/doc/openapi.yaml \
                swaggerapi/swagger-ui
        else
            echo "Could not read $openapi_path. Is it a file?"
        fi
    else
        echo "This script depends on podman"
    fi
}

function plantuml() {
    command_name=$0
    args=$*
    if [ -z ${1+x} ]; then
        echo "[!] Usage: $command_name <command>"
        echo "[!] Example: $command_name -o out diagrams"
    elif command -v podman 1>/dev/null 2>&1; then

        echo "[>] Running Plantuml CLI with args \"$args\" with podman."
        podman run \
            --rm \
            -v $PWD:/data \
            ghcr.io/plantuml/plantuml \
            $*
    else
        echo "This script depends on podman"
    fi
}

function cloc() {
    command_name=$0
    args=$*
    if [ -z ${1+x} ]; then
        echo "[!] Usage: $command_name <command>"
        echo "[!] Example: $command_name ."
    elif command -v podman 1>/dev/null 2>&1; then

        echo "[>] Running cloc CLI with args \"$args\" with podman."
        podman run \
            --rm \
            -v $PWD:/tmp \
            aldanial/cloc \
            $*
    else
        echo "This script depends on podman"
    fi
}
