
alias l="ls -halp"
alias ll="ls -hlp"
alias lm="ls -hp"

# alias ds="du -khd 1 . | sort -h"
ds(){
    du -khd 1 $@ | sort -h
}

alias gs='git status'
alias gl='git log'
alias gr='git restore'
alias glg='git log --graph'
alias glp='git log --pretty=oneline'

alias fetch_pull='git fetch $@ && git pull $@'

alias dockerlsa="docker container ls -a"
alias dockerls="docker container ls --format 'table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Names}}'"
alias dockeri="docker image"

alias dc="docker-compose"

export GOTO_EDITOR="vim"

case "$(uname -s)" in
    Linux)

		export ANDROID_HOME=$HOME/Android/Sdk
        export GTK_IM_MODULE=cedilla
        export QT_IM_MODULE=cedilla

		;;
	Darwin)
		export ANDROID_HOME="$HOME/Library/Android/sdk"

		;;
esac

export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

LINUX_BREW_BIN=/home/linuxbrew/.linuxbrew/bin

if [[ -d $LINUX_BREW_BIN ]] && [[ -x $LINUX_BREW_BIN/brew ]]; then
    export PATH=$PATH:$LINUX_BREW_BIN
    eval $($LINUX_BREW_BIN/brew shellenv)
fi
