# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"
#ZSH_THEME="gentoo"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

source $ZSH/oh-my-zsh.sh

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

export PATH="/usr/local/sbin:$PATH"

[[ -r $HOME/.goto/gt.sh ]] && source $HOME/.goto/gt.sh
[[ -r $HOME/.bash_profile ]] && source $HOME/.bash_profile
[[ -r $HOME/.autojump/etc/profile.d/autojump.sh ]] && source $HOME/.autojump/etc/profile.d/autojump.sh

export PATH="$HOME/.local/lib/flutter/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
